---
title: Shape It Up Nutrition and Fitness
timezone: America/New_York
collections:
  classes:
    title: Classes
    output: false
  events:
    title: Events
    output: false
  instructors:
    title: Instructors
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: classes
  values:
    published: true
    sub_heading: group exercise class
    class_type: dance fitness
    class_image: 
    additional_info: 
    button_link: 
    button_label: 
- scope:
    path: ''
    type: events
  values:
    published: true
    has_time_and_date: false
    event_date: 
    event_end_date: 
    class: 
    button_link: 
    button_label: 
- scope:
    path: ''
    type: instructors
  values:
    published: true
    classes:
    - Zumba
    image: 
url: https://shapeitupnutritionfitness.com
google_tracking: UA-77109672-1
